spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: local

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace




