spring:
  datasource:
    url: jdbc:mysql://localhost:3306/triple?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: user
    password: user


  sql:
    init:
      mode: always

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use+sql_comments: true

    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true